### ISSUE TITLE
Getting error while importing library

### ISSUE THREAD

**Issue by raghavagarwal701** [ComposioHQ/composio-pr-agent#1]
I am trying to clone the repo and run the code through main.py but while importing " from composio_langgraph import Action, App, ComposioToolSet, WorkspaceType" I am getting this error. I checked the versions of both the library both are v0.6.7 I also checked for any dependency issues but didn't find any.

python main.py 
Traceback (most recent call last):
  File "/Users/raghavagarwal/Downloads/Drizz/composio_test1/main.py", line 3, in <module>
    from agent import get_graph
  File "/Users/raghavagarwal/Downloads/Drizz/composio_test1/agent.py", line 18, in <module>
    from composio_langgraph import Action, App, ComposioToolSet, WorkspaceType
  File "/Users/raghavagarwal/Downloads/Drizz/venv/lib/python3.12/site-packages/composio_langgraph/__init__.py", line 3, in <module>
    from .toolset import ComposioToolSet
  File "/Users/raghavagarwal/Downloads/Drizz/venv/lib/python3.12/site-packages/composio_langgraph/toolset.py", line 1, in <module>
    from composio_langchain import ComposioToolSet as BaseComposioToolSet
  File "/Users/raghavagarwal/Downloads/Drizz/venv/lib/python3.12/site-packages/composio_langchain/__init__.py", line 3, in <module>
    from composio_langchain.toolset import ComposioToolSet
  File "/Users/raghavagarwal/Downloads/Drizz/venv/lib/python3.12/site-packages/composio_langchain/toolset.py", line 28, in <module>
    class ComposioToolSet(
TypeError: ComposioToolSet.__init_subclass__() got an unexpected keyword argument 'action_name_char_limit'

**Comment by shreysingla11** [comment]
Please update all the three packages: composio, composio_langchain, and composio_langgraph to v0.6.7
This issue should be fixed.

**Comment by raghavagarwal701** [comment]
I have composio_langgraph and composio_langchain at v0.6.7 but the composio has v0.1.0 which is up to date
